// Scans tests/cases/**/*.html and generates #[test] functions that call
// assert_html_case!(<absolute path>). Output goes to OUT_DIR/html_tests.rs,
// which tests/mod.rs include!s.
use std::{fs, path::PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let cases_dir = PathBuf::from(&manifest).join("tests/cases");
    let mut tests = String::new();
    tests.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n\n");

    if !cases_dir.exists() {
        let out = std::env::var("OUT_DIR").unwrap();
        fs::write(format!("{out}/html_tests.rs"), tests).unwrap();
        return;
    }

    let mut entries = walk(&cases_dir, &cases_dir);
    entries.sort();
    for (rel, abs) in entries {
        if abs.extension().and_then(|e| e.to_str()) != Some("html") {
            continue;
        }
        // function name: relative path, separators -> underscore
        let fn_name = rel
            .with_extension("")
            .to_string_lossy()
            .replace(['/', '\\', '-', ' '], "_");
        let abs_str = abs.to_str().unwrap();
        let content = fs::read_to_string(&abs).unwrap_or_default();
        let ignore_attr = if content.contains("data-ignore=\"true\"") {
            "#[ignore]\n"
        } else {
            ""
        };
        tests.push_str(&format!(
            "{ignore_attr}#[test]\nfn html__{fn_name}() {{\n    assert_html_case!(\"{abs_str}\");\n}}\n\n"
        ));
    }

    let out = std::env::var("OUT_DIR").unwrap();
    fs::write(format!("{out}/html_tests.rs"), tests).unwrap();
    println!("cargo:rerun-if-changed=tests/cases");
}

fn walk(root: &PathBuf, dir: &PathBuf) -> Vec<(PathBuf, PathBuf)> {
    let mut out = Vec::new();
    if let Ok(rd) = fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() {
                out.extend(walk(root, &p));
            } else {
                let rel = p.strip_prefix(root).unwrap().to_path_buf();
                out.push((rel, p));
            }
        }
    }
    out
}
