/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum OutputType {
  Bincode = 'bincode',
  Json = 'json',
  None = 'none'
}
export interface SourceCodePosition {
  line: number
  column: number
}
export interface CompileWarning {
  start: SourceCodePosition
  end: SourceCodePosition
  message: string
}
export interface FileResult {
  content?: Buffer
  warnings: Array<CompileWarning>
}
export interface CompileResult {
  files: Array<FileEntry>
  importIndex?: Buffer
}
export interface FileEntry {
  path: string
  file: FileResult
}
export interface CompileArgument {
  /** Source files to compile */
  src: Array<SourceEntry>
  /** Output encoding format */
  outputType: OutputType
  /** Prefix for tag name selectors, default "wx-" */
  tagNamePrefix?: string
}
export interface SourceEntry {
  path: string
  content: Buffer
}
export interface CompileSingleArgument {
  /** CSS file name */
  fileName: string
  /** CSS file content */
  fileContent: Buffer
  /** Output encoding format */
  outputType: OutputType
  /** Prefix for tag name selectors, default "wx-" */
  tagNamePrefix?: string
}
export declare function compileSync(args: CompileArgument): CompileResult
export declare function compileSingleSync(args: CompileSingleArgument): FileResult
export declare function compile(args: CompileArgument): Promise<CompileResult>
export declare function compileSingle(args: CompileSingleArgument): Promise<FileResult>
